version: '3'
services:
  mongo_hp:
    image: mongo
    container_name: mongo_hp
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
        #command: mongod --logpath=/dev/null # --quiet
    networks:
      - samplenetwork

  test_hp:
    build: test_delete
    container_name: test_hp
    restart: always
    ports:
      - 3044:3044
    links:
      - mongo_hp
    depends_on:
      - mongo_hp
    networks:
      - samplenetwork

  reverseproxy_hp:
    container_name: reverseproxy_hp
    build: reverse-proxy
    ports:
      - 8080:8080
      - 3000:3000
    restart: always
    networks:
      - samplenetwork
    links:
      - apirest_hp
      - apigraphql_hp

  apirest_hp:
    container_name: apirest_hp
    build: rest-api
    links:
      - mongo_hp
    depends_on:
      - mongo_hp
    restart: always
    networks:
      - samplenetwork

  apigraphql_hp:
    container_name: apigraphql_hp
    build: graphql-api
    restart: always
    networks:
      - samplenetwork

networks:
  samplenetwork:
    driver: bridge
