version: '3'
services:
  reverseproxy:
    build: ./reverse-proxy/.
    ports:
      - 8080:8080
      - 3000:3000
    restart: always

  apirest:
    build: ./rest-api/.
    depends_on:
      - reverseproxy
    restart: always

  apigraphql:
    build: ./graphql-api/.
    depends_on:
      - reverseproxy
    restart: always
